# Orchestration to connect Nextjs, Flask, and MySQL

services:

  db:
    container_name: qualisync-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: very_secure_password_for_qualisync
      MYSQL_DATABASE: fuchsia_atms_db
      MYSQL_USER: qualisync
      MYSQL_PASSWORD: password_qualisync_lol
    volumes: 
      - db-data:/var/lib/mysql 
      - ./server/db/migrations:/docker-entrypoint-initdb.d:ro
    ports:
      - "3307:3306" 
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", '--password=$${MYSQL_ROOT_PASSWORD}']
      interval: 10s 
      timeout: 5s 
      retries: 10 
      start_period: 10s 
    networks:
      - default 

  backend:
    container_name: qualisync-api
    build: ./server
    ports:
      - 5821:5821
    env_file:
      - ./server/.env
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - FLASK_API_HOST=0.0.0.0
      - FLASK_API_PORT=5821
    volumes:
      - ./server/db:/app/db
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      # RECOMMENDED HEALTH CHECK - add dedicated /health endpoint
      test: ["CMD-SHELL", "curl -f http://$${FLASK_API_HOST}:$${FLASK_API_PORT}/ || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks: 
      - default

  frontend:
    container_name: qualisync-web
    build: ./web
    ports:
      - 3000:3000
    env_file:
      - ./web/.env
    environment:
      - NEXT_PUBLIC_FLASK_API_URL=http://localhost:5821
    depends_on: 
      - backend
    networks: 
      - default

volumes:
  db-data: {}
