[tool.black]
line-length = 88
exclude = '\\b(venv|.venv|db|pycache)\\b'
target-version = ["py311"]

[tool.flake8]
line-length = 88
exclude = venv,.venv,db,pycache
ignore = E203,W503
max-complexity = 10
